//
// Created by Wouter Groeneveld on 10/07/20.
//

#ifndef GBA_BITMAP_ENGINE_PROJECT_TOOLBOX_H
#define GBA_BITMAP_ENGINE_PROJECT_TOOLBOX_H

#define GBA_SCREEN_WIDTH 240
#define GBA_SCREEN_WIDTH_FX GBA_SCREEN_WIDTH << 8
#define GBA_SCREEN_HEIGHT 160
#define GBA_SCREEN_HEIGHT_FX GBA_SCREEN_HEIGHT << 8

#define M4_WIDTH	GBA_SCREEN_WIDTH
#define M4_HEIGHT	GBA_SCREEN_HEIGHT

extern COLOR *vid_page;

#endif //GBA_BITMAP_ENGINE_PROJECT_TOOLBOX_H
